

"use client"
import Head from 'next/head';
import Image from 'next/image';
import NoSSR from "../../components/NoSSR.tsx";
import Header from '../../components/Chart/Header';
import TopCards from '../../components/Chart/TopCards';
// import BarChart from '../../components/Chart/BarChart.jsx';
import RecentOrders from '../../components/Chart/RecentOrders';
import dynamic from "next/dynamic";
const BarChart = dynamic(() => import("../../components/Chart/BarChart.jsx"), {
    ssr: true,
});



export default function Home() {
    return (
        <div className='py-[200px] px-[15px] md:px-[50px] '>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='bg-gray-100 min-h-screen'>
                <Header />
                <TopCards />
                <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
                    <NoSSR>
                        <BarChart />
                    </NoSSR>
                    <RecentOrders />
                </div>
            </main>
        </div>
    );
}
